apiVersion: v1
entries:
  cert-manager-webhook-hetzner:
  - apiVersion: v1
    appVersion: 1.12.3
    created: "2023-08-19T17:48:44.729335+02:00"
    description: Allow cert-manager to solve DNS challenges using Hetzner DNS API
    digest: ffab0388e49bda51c592298306ebf314b6754d571ce030525455d33f28e5dd0b
    name: cert-manager-webhook-hetzner
    urls:
    - https://devconsole-de.github.io/cert-manager-webhook-hetzner/cert-manager-webhook-hetzner-1.5.0.tgz
    version: 1.5.0
generated: "2023-08-19T17:48:44.728236+02:00"
